# Writes an NSIS include with three macros for a staged install tree:
#   !macro <MACRO>_INSTALL             SetOutPath/File lines for every staged file
#   !macro <MACRO>_UNINSTALL <dir>     matching Delete lines under <dir>, then
#                                      RMDir for the subdirectories (deepest
#                                      first, never recursive)
#   !macro <MACRO>_MANIFEST <handle>   FileWrite lines naming every staged file,
#                                      relative to the install directory, for
#                                      install-manifest.txt (see openmm2.nsi)
# so setup and the uninstaller remove exactly what was installed.
#
#   cmake -DSTAGE=<dir> -DOUTPUT=<file.nsh> -DMACRO=OPENMM2_APP
#         [-DWINE_PATHS=ON] -P GenerateFileList.cmake
#
# Source paths are written in the host's native form. WINE_PATHS=ON writes
# them as Z:\... for running the Windows makensis under Wine.

cmake_minimum_required(VERSION 3.25)

foreach(var STAGE OUTPUT MACRO)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "GenerateFileList.cmake: ${var} is required")
    endif()
endforeach()

function(_nsis_escape out value)
    string(REPLACE "$" "$$" value "${value}")
    set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(_source_path out path)
    if(WINE_PATHS)
        string(REPLACE "/" "\\" path "Z:${path}")
    else()
        cmake_path(NATIVE_PATH path path)
    endif()
    _nsis_escape(path "${path}")
    set(${out} "${path}" PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE files LIST_DIRECTORIES false RELATIVE "${STAGE}" "${STAGE}/*")
list(SORT files)

set(install "; Generated by packaging/windows/GenerateFileList.cmake. Do not edit.\n")
string(APPEND install "!macro ${MACRO}_INSTALL\n")
set(uninstall "!macro ${MACRO}_UNINSTALL base\n")
set(manifest "!macro ${MACRO}_MANIFEST handle\n")
set(dirs)
set(current_dir "<none>")
foreach(rel IN LISTS files)
    # install-manifest.txt is written with FileWrite, which converts to the
    # ANSI code page: keep the names plain ASCII so the file reads the same
    # everywhere. The names are ours (programs, licences, fonts).
    if(NOT rel MATCHES "^[A-Za-z0-9 ._+/-]+$")
        message(FATAL_ERROR "GenerateFileList.cmake: unsupported characters in staged file name '${rel}'")
    endif()
    cmake_path(GET rel PARENT_PATH dir)
    if(NOT dir STREQUAL current_dir)
        set(current_dir "${dir}")
        if(dir STREQUAL "")
            string(APPEND install "    SetOutPath \"$INSTDIR\"\n")
        else()
            string(REPLACE "/" "\\" dir_win "${dir}")
            _nsis_escape(dir_win "${dir_win}")
            string(APPEND install "    SetOutPath \"$INSTDIR\\${dir_win}\"\n")
            # Record the directory and all its parents for removal.
            set(d "${dir}")
            while(NOT d STREQUAL "")
                list(APPEND dirs "${d}")
                cmake_path(GET d PARENT_PATH d)
            endwhile()
        endif()
    endif()
    _source_path(src "${STAGE}/${rel}")
    string(APPEND install "    File \"${src}\"\n")
    string(REPLACE "/" "\\" rel_win "${rel}")
    _nsis_escape(rel_win "${rel_win}")
    string(APPEND uninstall "    Delete \"\${base}\\${rel_win}\"\n")
    string(APPEND manifest "    FileWrite \${handle} \"${rel_win}$\\r$\\n\"\n")
endforeach()

# Deepest directories first.
list(REMOVE_DUPLICATES dirs)
set(keyed)
foreach(d IN LISTS dirs)
    string(REGEX REPLACE "[^/]" "" slashes "${d}")
    string(LENGTH "${slashes}" depth)
    math(EXPR key "1000 - ${depth}")
    list(APPEND keyed "${key}|${d}")
endforeach()
list(SORT keyed)
foreach(entry IN LISTS keyed)
    string(REGEX REPLACE "^[0-9]+\\|" "" d "${entry}")
    string(REPLACE "/" "\\" d_win "${d}")
    _nsis_escape(d_win "${d_win}")
    string(APPEND uninstall "    RMDir \"\${base}\\${d_win}\"\n")
endforeach()

string(APPEND install "!macroend\n")
string(APPEND uninstall "!macroend\n")
string(APPEND manifest "!macroend\n")
file(WRITE "${OUTPUT}" "${install}\n${uninstall}\n${manifest}")
