// City and race data commands: psdlinfo, psdl2obj, instinfo, baiinfo, pvsinfo,
// races, citycheck.
#include "Command.h"
#include "Common.h"
#include "city/CityData.h"
#include "city/CityMesh.h"
#include "city/Psdl.h"
#include "core/File.h"
#include "core/StringUtil.h"
#include "vfs/GameSource.h"

#include <array>
#include <format>
#include <map>
#include <print>
#include <set>

namespace mm2::tool {
namespace {

std::optional<city::Psdl> loadPsdl(const vfs::FileSystem& fs, const std::string& cityName) {
    const std::string path = str::iendsWith(cityName, ".psdl") ? cityName : "city/" + cityName + ".psdl";
    auto bytes = readFile(fs, path);
    if (!bytes)
        return std::nullopt;
    std::string err;
    auto p = city::parsePsdl(*bytes, &err);
    if (!p)
        std::println(stderr, "error: {}: {}", path, err);
    return p;
}

int cmdPsdlInfo(std::span<char* const> args) {
    if (args.size() < 2)
        return 2;
    auto fs = openContainer(args[0]);
    if (!fs)
        return 1;
    auto p = loadPsdl(*fs, args[1]);
    if (!p)
        return 1;
    std::println("vertices {}  heights {}  textures {}  rooms {}  roads {}  firstRoadRoom {}",
                 p->vertices.size(), p->heights.size(), p->textures.size(), p->rooms.size() - 1,
                 p->roads.size(), p->firstRoadRoom);
    std::println(
        "bounds ({:.1f} {:.1f} {:.1f}) .. ({:.1f} {:.1f} {:.1f})  sphere ({:.1f} {:.1f} {:.1f}) r {:.1f}",
        p->bounds.min.x, p->bounds.min.y, p->bounds.min.z, p->bounds.max.x, p->bounds.max.y, p->bounds.max.z,
        p->sphereCenter.x, p->sphereCenter.y, p->sphereCenter.z, p->sphereRadius);
    std::array<std::size_t, city::kPsdlAttrTypeCount> counts{};
    std::map<int, std::size_t> flags;
    for (std::size_t r = 1; r < p->rooms.size(); ++r) {
        ++flags[p->rooms[r].flags];
        for (const auto& a : p->rooms[r].attributes)
            ++counts[static_cast<int>(a.type)];
    }
    std::println("attributes:");
    for (int t = 0; t < city::kPsdlAttrTypeCount; ++t)
        std::println("  {:<18} {}", city::psdlAttrTypeName(static_cast<city::PsdlAttrType>(t)), counts[t]);
    std::println("room flags:");
    for (const auto& [f, n] : flags)
        std::println("  0x{:02x}  {}", f, n);
    const auto problems = city::validatePsdl(*p);
    for (const auto& s : problems)
        std::println("problem: {}", s);
    auto mesh = city::buildCityMesh(*p);
    std::println("mesh: {} triangles, {} vertices", mesh.triangleCount(), mesh.vertexCount());
    if (args.size() > 2) { // dump one room
        const auto room = static_cast<std::size_t>(str::parseInt(args[2]).value_or(0));
        if (room > 0 && room < p->rooms.size()) {
            const auto& rm = p->rooms[room];
            std::print("room {} flags 0x{:02x} propRule {} perimeter:", room, rm.flags, rm.propRule);
            for (const auto& pt : rm.perimeter)
                std::print(" {}->{}", pt.vertex, pt.neighbor);
            std::println("");
            // Where the perimeter runs (x z, and the centre of its points).
            Vec3 centre;
            int counted = 0;
            std::print("  at:");
            for (const auto& pt : rm.perimeter)
                if (pt.vertex < p->vertices.size()) {
                    const Vec3& v = p->vertices[pt.vertex];
                    std::print(" ({:.1f} {:.1f})", v.x, v.z);
                    centre = centre + v;
                    ++counted;
                }
            if (counted > 0)
                std::print("  centre ({:.1f} {:.1f} {:.1f})", centre.x / static_cast<float>(counted),
                           centre.y / static_cast<float>(counted), centre.z / static_cast<float>(counted));
            std::println("");
            for (const auto& a : rm.attributes) {
                std::print("  {}{} sub {}:", city::psdlAttrTypeName(a.type), a.last ? "*" : "", a.subtype);
                for (auto w : a.args)
                    std::print(" {}", w);
                if (a.type == city::PsdlAttrType::Texture && p->texture(a.textureBase()))
                    std::print("  ({})", *p->texture(a.textureBase()));
                std::println("");
            }
        }
    }
    return problems.empty() ? 0 : 1;
}

// Writes the city mesh as Wavefront OBJ with one group per texture.
int cmdPsdl2Obj(std::span<char* const> args) {
    if (args.size() < 3)
        return 2;
    auto fs = openContainer(args[0]);
    if (!fs)
        return 1;
    auto p = loadPsdl(*fs, args[1]);
    if (!p)
        return 1;
    city::CityMeshOptions opt;
    opt.includeFacadeBounds = args.size() > 3 && std::string_view(args[3]) == "--bounds";
    const auto mesh = city::buildCityMesh(*p, opt);

    // Group all rooms' batches by texture/kind for a compact file.
    std::string out = std::format("# {} city mesh generated by mm2tool psdl2obj\n", args[1]);
    std::size_t base = 1;
    for (std::size_t room = 1; room < mesh.rooms.size(); ++room) {
        for (const auto& b : mesh.rooms[room].batches) {
            const std::string* tex = p->texture(b.texture);
            out += std::format("g room{}_{}\nusemtl {}\n", room, city::surfaceKindName(b.kind),
                               tex && !tex->empty() ? *tex : std::string("none"));
            for (const auto& v : b.vertices)
                out += std::format("v {:.3f} {:.3f} {:.3f}\nvt {:.4f} {:.4f}\nvn {:.3f} {:.3f} {:.3f}\n",
                                   v.position.x, v.position.y, v.position.z, v.uv.x, 1.0f - v.uv.y,
                                   v.normal.x, v.normal.y, v.normal.z);
            for (std::size_t i = 0; i + 2 < b.indices.size(); i += 3) {
                const std::size_t a = base + b.indices[i], c = base + b.indices[i + 1],
                                  d = base + b.indices[i + 2];
                out += std::format("f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n", a, c, d);
            }
            base += b.vertices.size();
        }
    }
    if (!file::writeAtomic(str::toPath(args[2]), out)) {
        std::println(stderr, "error: cannot write {}", args[2]);
        return 1;
    }
    std::println("wrote {} ({} triangles)", args[2], mesh.triangleCount());
    return 0;
}

std::string_view asText(const std::vector<std::byte>& b) {
    return {reinterpret_cast<const char*>(b.data()), b.size()};
}

int cmdInstInfo(std::span<char* const> args) {
    if (args.size() < 2)
        return 2;
    auto fs = openContainer(args[0]);
    if (!fs)
        return 1;
    const std::string path =
        str::iendsWith(args[1], ".inst") ? args[1] : std::format("city/{}.inst", args[1]);
    auto bytes = readFile(*fs, path);
    if (!bytes)
        return 1;
    std::string err;
    auto inst = city::parseInst(*bytes, &err);
    if (!inst) {
        std::println(stderr, "error: {}: {}", path, err);
        return 1;
    }
    std::map<std::string, int> models;
    int rotY = 0;
    for (const auto& i : *inst) {
        ++models[i.name];
        rotY += i.rotY;
    }
    std::println("{} instances ({} compact rotY), {} distinct models", inst->size(), rotY, models.size());
    const bool all = args.size() > 2 && std::string_view(args[2]) == "--all";
    for (std::size_t k = 0; k < inst->size() && (all || k < 20); ++k) {
        const auto& i = (*inst)[k];
        std::println("  room {:4} flags 0x{:04x} {} {} pos ({:.2f} {:.2f} {:.2f})", i.room, i.flags,
                     i.rotY ? "rotY" : "mtx ", i.name, i.transform.m3.x, i.transform.m3.y, i.transform.m3.z);
    }
    return 0;
}

int cmdBaiInfo(std::span<char* const> args) {
    if (args.size() < 2)
        return 2;
    auto fs = openContainer(args[0]);
    if (!fs)
        return 1;
    const std::string path = str::iendsWith(args[1], ".bai") ? args[1] : std::format("city/{}.bai", args[1]);
    auto bytes = readFile(*fs, path);
    if (!bytes)
        return 1;
    std::string err;
    auto map = city::parseBai(*bytes, &err);
    if (!map) {
        std::println(stderr, "error: {}: {}", path, err);
        return 1;
    }
    std::size_t sections = 0, lanes = 0;
    std::map<int, int> flags;
    for (const auto& p : map->paths) {
        sections += p.sectionCount();
        lanes += p.left.numLanes + p.right.numLanes;
        ++flags[p.flags];
    }
    std::println("{} paths ({} sections, {} lanes), {} intersections, room tables for {} rooms",
                 map->paths.size(), sections, lanes, map->intersections.size(), map->roomPathsNear.size());
    for (const auto& [f, n] : flags)
        std::println("  path flags 0x{:02x}: {}", f, n);
    if (args.size() > 2) {
        const auto id = static_cast<std::size_t>(str::parseInt(args[2]).value_or(0));
        if (id < map->paths.size()) {
            const auto& p = map->paths[id];
            std::print("path {} flags 0x{:x} halfWidth {} speed {} rooms", p.id, p.flags, p.halfWidth,
                       p.speedLimit);
            for (auto r : p.rooms)
                std::print(" {}", r);
            std::println("");
            for (const auto* s : {&p.left, &p.right})
                std::println("  side lanes {} trams {} trains {} sidewalks {} type {} polylines {}",
                             s->numLanes, s->numTrams, s->numTrains, s->numSidewalks, s->roadType,
                             s->polylines.size());
            for (std::size_t i = 0; i < p.center.size(); ++i)
                std::println("  section {} ({:.2f} {:.2f} {:.2f})", i, p.center[i].x, p.center[i].y,
                             p.center[i].z);
            for (const auto& e : p.ends)
                std::println("  end -> intersection {} rule {} roadIndex {}", e.intersection, e.vehicleRule,
                             e.roadIndex);
        }
    }
    return 0;
}

int cmdRaces(std::span<char* const> args) {
    if (args.size() < 2)
        return 2;
    std::string err;
    auto source = vfs::probeGameSource(str::toPath(args[0]), &err);
    if (!source) {
        std::println(stderr, "error: {}", err);
        return 1;
    }
    vfs::Vfs v;
    if (!vfs::mountGameSource(v, *source, &err)) {
        std::println(stderr, "error: {}", err);
        return 1;
    }
    for (const auto& c : city::listCities(v)) {
        if (!str::iequals(c.mapName, args[1]) && !str::iequals(c.localizedName, args[1]))
            continue;
        std::println("{} (map {}, races in race/{}/)", c.localizedName, c.mapName, c.raceDir);
        for (const auto& r : city::listRaces(v, c)) {
            std::print("  {:<12} {:2}  {:<28}", city::raceModeName(r.mode), r.index, r.name);
            if (r.settings)
                std::print(" laps {} opp {} cops {} time {} | pro laps {} opp {} time {}",
                           r.settings->amateur.numLaps, r.settings->amateur.opponents,
                           r.settings->amateur.cops, r.settings->amateur.timeLimit,
                           r.settings->professional.numLaps, r.settings->professional.opponents,
                           r.settings->professional.timeLimit);
            std::println("");
        }
        return 0;
    }
    std::println(stderr, "error: no city '{}'", args[1]);
    return 1;
}

// Parses every city and race file; exits non-zero if a file the game uses
// fails. Unreferenced editor leftovers are reported but tolerated.
int cmdCityCheck(std::span<char* const> args) {
    if (args.empty())
        return 2;
    std::string err;
    auto source = vfs::probeGameSource(str::toPath(args[0]), &err);
    if (!source) {
        std::println(stderr, "error: {}", err);
        return 1;
    }
    vfs::Vfs v;
    if (!vfs::mountGameSource(v, *source, &err)) {
        std::println(stderr, "error: {}", err);
        return 1;
    }

    // Files the game references through the city/race definitions.
    std::set<std::string> referenced;
    int fatal = 0;
    for (const auto& info : city::listCities(v)) {
        auto c = city::loadCity(v, info.mapName, &err);
        if (!c) {
            std::println("FAIL city {}: {}", info.mapName, err);
            ++fatal;
            continue;
        }
        const auto meshTris = city::buildCityMesh(c->psdl).triangleCount();
        std::println("city {:<8} rooms {} instances {}+{} paths {} intersections {} races {} mesh {} tris",
                     info.mapName, c->psdl.roomCount() - 1, c->instances.size(), c->aiInstances.size(),
                     c->aiMap ? c->aiMap->paths.size() : 0, c->aiMap ? c->aiMap->intersections.size() : 0,
                     c->races.size(), meshTris);
        for (const auto& w : c->warnings)
            std::println("  warning: {}", w);
        for (const auto& p : city::validatePsdl(c->psdl)) {
            std::println("  FAIL psdl: {}", p);
            ++fatal;
        }
        if (c->aiMap)
            for (const auto& p : city::validateAiMap(*c->aiMap, c->psdl.roomCount())) {
                std::println("  FAIL bai: {}", p);
                ++fatal;
            }
        const std::string raceDir = "race/" + str::lower(info.raceDir) + "/";
        for (const auto& r : c->races) {
            for (const auto* f :
                 {&r.waypoints, &r.aiMap, &r.aiMapPro, &r.pathSet, &r.crashEvents, &r.crashEventsPro})
                if (!f->empty())
                    referenced.insert(*f);
            for (const auto* cfgPath : {&r.aiMap, &r.aiMapPro}) {
                if (cfgPath->empty())
                    continue;
                if (auto b = v.readAll(*cfgPath))
                    if (auto cfg = city::parseAiMapConfig(asText(*b)))
                        for (const auto& o : cfg->opponents)
                            referenced.insert(raceDir + str::lower(o.pathFile));
            }
            for (const auto* evPath : {&r.crashEvents, &r.crashEventsPro}) {
                if (evPath->empty())
                    continue;
                if (auto b = v.readAll(*evPath))
                    if (auto ev = city::parseCrashEvents(asText(*b)))
                        for (const auto& e : *ev)
                            referenced.insert(raceDir + str::lower(e.file) + ".csv");
            }
        }
    }

    struct Stat {
        int ok = 0, failed = 0;
    };
    std::map<std::string, Stat> stats;
    auto check = [&](const std::string& kind, const std::string& path, bool ok, const std::string& why) {
        auto& s = stats[kind];
        if (ok) {
            ++s.ok;
            return;
        }
        ++s.failed;
        const bool isRef = referenced.contains(path);
        std::println("{} {}: {}", isRef ? "FAIL" : "note (unreferenced)", path, why);
        if (isRef)
            ++fatal;
    };
    for (const auto& e : v.listFiles()) {
        const std::string& p = e.path;
        if (!p.starts_with("city/") && !p.starts_with("race/") && !p.starts_with("tune/"))
            continue;
        const auto name = p.substr(p.rfind('/') + 1);
        if (name.starts_with(".#"))
            continue; // CVS conflict backups
        auto bytes = v.readAll(p);
        if (!bytes) {
            check("unreadable", p, false, "read failed");
            continue;
        }
        err.clear();
        if (p.ends_with(".psdl")) {
            auto ps = city::parsePsdl(*bytes, &err);
            check("psdl", p, ps && city::validatePsdl(*ps).empty(), err.empty() ? "validation failed" : err);
        } else if (p.ends_with(".inst")) {
            check("inst", p, city::parseInst(*bytes, &err).has_value(), err);
        } else if (p.ends_with(".cpvs")) {
            check("cpvs", p, city::parseCpvs(*bytes, &err).has_value(), err);
        } else if (p.ends_with(".bai")) {
            check("bai", p, city::parseBai(*bytes, &err).has_value(), err);
        } else if (p.ends_with(".pathset")) {
            check("pathset", p, city::parsePathSet(*bytes, &err).has_value(), err);
        } else if (p.ends_with(".opp")) {
            check("opp", p, city::parseOpponentPath(asText(*bytes), &err).has_value(), err);
        } else if (p.ends_with(".aimap") || p.ends_with(".aimap_p")) {
            check("aimap", p, city::parseAiMapConfig(asText(*bytes), &err).has_value(), err);
        } else if (p.ends_with("waypoints.csv")) {
            check("waypoints", p, city::parseWaypoints(asText(*bytes), &err).has_value(), err);
        } else if (p.starts_with("race/") && name.starts_with("mm") && name.ends_with("data.csv")) {
            check("racetable", p, city::parseRaceTable(asText(*bytes), &err).has_value(), err);
        } else if (p.starts_with("race/") && name.starts_with("crash") &&
                   name.find("data") != std::string::npos && name.ends_with(".csv")) {
            check("crashdata", p, city::parseCrashEvents(asText(*bytes), &err).has_value(), err);
        } else if (p.starts_with("race/") && name.ends_with(".csv") && referenced.contains(p)) {
            check("eventpoints", p, city::parseWaypoints(asText(*bytes), &err).has_value(), err);
        } else if (p.starts_with("city/") && name.size() > 5 && name.find(".lt") == name.size() - 5) {
            check("lighting", p, city::parseLighting(asText(*bytes), &err).has_value(), err);
        } else if (p.ends_with("_fog.csv")) {
            check("fog", p, city::parseFogTable(asText(*bytes), &err).has_value(), err);
        } else if (p.ends_with(".lmap")) {
            check("lmap", p, city::parseLightMap(*bytes, &err).has_value(), err);
        } else if (p.ends_with(".mtl")) {
            check("mtl", p, city::parseMaterialLibrary(asText(*bytes), &err).has_value(), err);
        }
    }
    // Referenced files that do not exist.
    for (const auto& r : referenced)
        if (!v.exists(r)) {
            std::println("FAIL missing referenced file {}", r);
            ++fatal;
        }
    std::println("\n{:<12} {:>6} {:>6}", "kind", "ok", "failed");
    for (const auto& [kind, s] : stats)
        std::println("{:<12} {:>6} {:>6}", kind, s.ok, s.failed);
    std::println("{} referenced files; {} fatal problems", referenced.size(), fatal);
    return fatal ? 1 : 0;
}

const Registrar r1({"psdlinfo", "<container> <city|path.psdl> [room]", "summarise a PSDL city file",
                    &cmdPsdlInfo});
const Registrar r2({"psdl2obj", "<container> <city|path.psdl> <out.obj> [--bounds]",
                    "export the PSDL street mesh as Wavefront OBJ", &cmdPsdl2Obj});
const Registrar r3({"instinfo", "<container> <city|path.inst> [--all]", "list city instances", &cmdInstInfo});
const Registrar r4({"baiinfo", "<container> <city|path.bai> [path id]", "summarise an AI road network",
                    &cmdBaiInfo});
const Registrar r5({"races", "<game source> <city>", "list a city's race events and settings", &cmdRaces});
const Registrar r6({"citycheck", "<game source>", "parse and validate every city and race file",
                    &cmdCityCheck});

} // namespace
} // namespace mm2::tool
