#pragma once

// Level collision polygons from the PSDL: a port of sdlPage16::Collect (MM2
// build 3393). lvlSDL::CollidePolyToLevel asks every room a body touches for
// its polygons near the body's bounding sphere, and sdlPage16::CollideSegment
// (wheel probes) does the same for a segment. The polygons are generated by
// Collect's own rules, not from the render mesh: road and sidewalk surfaces,
// curb walls, divider walls and tops, tunnel walls and railings, invisible
// facade bounds, roofs. Rules per attribute: docs/formats/psdl.md,
// "Collision polygons (sdlPage16::Collect)".

#include "city/Environment.h"
#include "city/Psdl.h"
#include "core/Math.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <span>
#include <string_view>
#include <vector>

namespace mm2::city {

// Room for generated vertices after the PSDL vertices in lvlSDL's vertex array
// (lvlSDL::LoadBinary allocates vertexCount + 0x200). The sdlPoly setters count
// it down per generated vertex but never check it.
inline constexpr int kSdlGeneratedVertexBudget = 0x200;

// sdlPoly: a phPolygon whose vertex indices point into SdlPolyBuffer::vertices.
// MM2 stores the indices as 16-bit values; every retail city stays below 65,536
// vertices including the generated ones, so nothing is truncated here.
struct SdlPoly {
    // v[3] == 0 marks a triangle, exactly as sdlPoly::InitNoArea's last argument
    // does (so a quad whose fourth corner is PSDL vertex 0 reads as a triangle).
    std::array<std::uint32_t, 4> v{};
    // sdlPoly::InitNoArea's normal: normalize((v2 - v1) x (v0 - v1)), or exactly
    // (0, 1, 0) when v0, v1 and v2 share their y. InitNoArea also fills the
    // polygon's edge normals (phPolygon::ComputeEdgeNormalCross); they are not
    // stored here and follow from the vertices.
    Vec3 normal;
    // phPolygon's material byte (the low byte of its area field): lvlSDL's
    // material index (see sdlTextureMaterials), resolved by
    // lvlLevelBound::GetMaterial.
    std::uint8_t material = 0;
};

// lvlSDL's collection buffer. `vertices` starts as the PSDL's vertices; the
// sdlPoly setters append generated ones (sdlPoly::sm_Count). MM2's polygon
// buffer is a static array of 256 phPolygons; here `polys` grows.
struct SdlPolyBuffer {
    std::vector<Vec3> vertices;
    std::vector<SdlPoly> polys;
    std::size_t psdlVertexCount = 0;
    // sdlPoly's countdown of generated vertices (a global in MM2). Below zero,
    // MM2 would have written past lvlSDL's vertex array; the vector just grows.
    int vertexBudget = kSdlGeneratedVertexBudget;

    // What lvlSDL::CollidePolyToLevel (and lvlSDL::CollideProbe) do before a
    // collection: sm_Count back to the PSDL vertex count, budget to 0x200.
    // Also clears `polys`.
    void reset(const Psdl& psdl);
    std::size_t generatedVertexCount() const { return vertices.size() - psdlVertexCount; }
};

// The query sphere Collect gets as a Vector4 (centre, radius).
// lvlSDL::CollidePolyToLevel passes the body's matrix position and its bound's
// bounding-sphere radius; lvlSDL::CollideProbe passes the probe segment's
// midpoint and 0.51 times its length.
struct SdlSphere {
    Vec3 center;
    float radius = 0;
};

// sdlPage16::Collect for one room: appends the room's collision polygons near
// `sphere` (null: no culling, every polygon) to out.polys and returns how many
// it added.
//
// `textureMaterials`: lvlSDL's texture -> material table (sdlTextureMaterials).
// `capacity`: polygon attempts allowed. Collect counts it down before every
//   polygon it tries, including ones InitNoArea then rejects as degenerate, and
//   returns early once it would go below zero; *overflow is then set to true
//   (it is left alone otherwise).
// `state`: Collect's in/out `int&`. On entry, where to start: (word offset of an
//   attribute in the room's attribute list << 11) | current texture value; 0 =
//   from the start. On an early return Collect writes the state of the attribute
//   it was in (its start, the texture before it), or 0 when that is the first
//   attribute processed in this call; it leaves the state alone when it
//   finishes. lvlSDL::CollidePolyToLevel shares one state (initially 0) across
//   all the rooms of a call and reports "buffer overflow" whenever it is
//   nonzero after a room; sdlPage16::CollideSegment calls again with the state
//   to continue. Null: start at 0.
// `probeRoom`: the room id lvlSDL::CollideProbe stores in a global while it
//   collides wheel probes (0 otherwise, e.g. in CollidePolyToLevel). When that
//   room has RoomFlag::SpecialBound, road, rectangle and divided-road surfaces
//   become triangles with their sidewalks raised as vertex copies.
int collectRoomPolygons(const Psdl& psdl, std::size_t room, const SdlSphere* sphere,
                        std::span<const std::uint8_t> textureMaterials, SdlPolyBuffer& out, int capacity,
                        bool* overflow = nullptr, std::uint32_t* state = nullptr,
                        std::uint16_t probeRoom = 0);

// lvlSDL's texture -> material table (built by lvlSDL::LoadBinary, shared by
// every sdlPage16).
// Index = MM2's texture index: entry 0 is 0 (no texture), entry i belongs to
// psdl.textures[i - 1] (a Texture attribute's value, plus the offset Collect
// adds per surface). Each value is the material index of the texture's row in
// city/materials.csv: materialIndex(name), 1-based into lvlMaterialMgr, 0 for
// rows whose material is "none" or unknown and for textures without a row.
// lvlLevelBound::GetMaterial maps 0 to the default material and n to
// lvlMaterialMgr entry n - 1. Texture names ending in a movie frame suffix
// "-0nnn" are looked up without it ("s_thames-0009" -> "s_thames"). Where
// materials.csv lists a texture twice the first row wins (HashTable::Insert).
std::vector<std::uint8_t> sdlTextureMaterials(const Psdl& psdl,
                                              std::span<const TextureMaterial> textureMaterials,
                                              const std::function<int(std::string_view)>& materialIndex);

// lvlMaterialMgr's 1-based index of a material as lvlSDL::LoadBinary stores it,
// for the materials cityLevel::Load reads from city/materials.mtl: entry 0 of
// lvlMaterialMgr is its built-in "default" material (index 1), then every new
// name in file order ("_default" is a new name; a repeated name, or "default",
// is not added again). 0 when `name` is not there. With the retail file:
// deepwater 2, _default 3, grass 4, water 5, dirt 6, sand 7, cobblestone 8,
// wood 9.
int sdlMaterialIndex(std::span<const PhysMaterial> materials, std::string_view name);

} // namespace mm2::city
